### ISSUE TITLE
org-freemind-export-to-freemind would remove TODO tag for task

### ISSUE THREAD

**Issue by yubrshen** [Fuco1/org-mode#2]
With emacs 25 /spacemacs 0.300 on Ubuntu 16.04, I tried to export org-mode file to freemind 
It worked almost. I found the problem that in the exported .mm file a head line of "TODO Task one" became "Task one". 
Here attached the files:

[missing-TODO-tag.zip](https://github.com/Fuco1/org-mode/files/1621439/missing-TODO-tag.zip)
test.org: the file to be exported
test.mm: the result of export

**Comment by Fuco1** [comment]
This is just a mirror of org-mode not an official repository.  You need to submit the issue to org mode.

**Comment by yubrshen** [comment]
Sorry, mixed up. Do you know where is the official repo?

Thanks,

**Comment by Fuco1** [comment]
They use a mailing list https://orgmode.org/worg/org-mailing-list.html
